name: bitrix_local

services:
  nginx:
    image: nginx:latest
    platform: linux/arm64
    environment:
      TZ: Europe/Moscow
    ports:
      - "80:80"
    volumes:
      - ../bitrix-projects:/var/www
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - php-site1

  php-site1:
    platform: linux/arm64
    image: ${BITRIX_PHP_IMAGE:-bitrix-php:8.4-v1}
    environment:
      TZ: Europe/Moscow
    extra_hosts:
      - "site1.local:host-gateway"
    volumes:
      - ../bitrix-projects/site1/www:/var/www/site1/www
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini

  mysql-site1:
    image: mysql:8.0
    platform: linux/arm64
    restart: always
    environment:
      TZ: Europe/Moscow
      MYSQL_ROOT_PASSWORD: bitrix_root_password
      MYSQL_DATABASE: bitrix
      MYSQL_USER: bitrix
      MYSQL_PASSWORD: bitrix_password
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone=+03:00
    volumes:
      - mysql_site1_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    platform: linux/arm64
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  mailpit:
    image: axllent/mailpit:latest
    platform: linux/arm64
    ports:
      - "8025:8025"

  cron-site1:
    platform: linux/arm64
    image: ${BITRIX_PHP_IMAGE:-bitrix-php:8.4-v1}
    environment:
      TZ: Europe/Moscow
    volumes:
      - ../bitrix-projects/site1/www:/var/www/site1/www
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    command: ["sh", "-lc", "while true; do php -f /var/www/site1/www/bitrix/modules/main/tools/cron_events.php; sleep 60; done"]
    depends_on:
      - mysql-site1
      - php-site1
  phpmyadmin:
    image: phpmyadmin:latest
    platform: linux/arm64
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: mysql-site1
      PMA_VERBOSE: site1
      UPLOAD_LIMIT: 1024M
    ports:
      - "8080:80"
volumes:
  mysql_site1_data:
  redis_data:
