server {
    listen 80;
    server_name nek.local;

    root /var/www/nek/www;
    index index.php index.html;

    charset utf-8;
    client_max_body_size 1024M;

    location / {
        try_files $uri $uri/ /bitrix/urlrewrite.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php-nek:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
